added some basic argument error detection

diff --git a/bin/bashdatacatalog-execdir b/bin/bashdatacatalog-execdir
--- a/bin/bashdatacatalog-execdir
+++ b/bin/bashdatacatalog-execdir
@@ -28,7 +28,8 @@ combined_catalog=$(mktemp)
 temp_file=$(mktemp)
 
 if [ "$#" -eq 0 ]; then
-    echo "./,file://${PWD},1," >> ${combined_catalog}
+    echo "error: no catalogs or collections provided" 1>&2
+    exit 1 
 fi
 
 while [ $# -gt 0 ]; do
@@ -46,6 +47,11 @@ while [ $# -gt 0 ]; do
 done
 
 while read COLLECTION_LINE; do
+    num_commas=$(echo "$COLLECTION_LINE" | awk -F',' '{print NF-1}')
+    if [ $num_commas -ne 3 ]; then
+           echo "error: incorrect number of columns in a catalog (there should be 4 columns; check for blank or trailing lines)" 1>&2
+           exit 1
+    fi
     BDC_COLLECTION_PREFIX=$(echo "$COLLECTION_LINE" | awk -F',' '{print $1}' | sed 's#/*$#/#g')
     BDC_COLLECTION_URL=$(echo "$COLLECTION_LINE" | awk -F',' '{print $2}' | sed 's#/*$#/#g')
     mkdir -p $BDC_COLLECTION_PREFIX
diff --git a/bin/bashdatacatalog-list b/bin/bashdatacatalog-list
--- a/bin/bashdatacatalog-list
+++ b/bin/bashdatacatalog-list
@@ -111,7 +111,7 @@ function trim_scoped_list() {
         cp ${temp_file} ${working_list}
     fi
 
-    grep "${BDC_LIST_PATTERN}" ${working_list} > ${temp_file}
+    grep "${BDC_LIST_PATTERN}" ${working_list} > ${temp_file} || :
     cp ${temp_file} ${working_list}
 
     if [ -f .temporal_assets.sed ]; then
@@ -263,6 +263,8 @@ while getopts "anstr:p:mwuf:ech" FLAG; do
             ;;
         r)
             BDC_LIST_RANGE=${OPTARG}
+            VALID_REGEX='^[0-9][0-9][0-9][0-9]\(-[0-1][0-9]\)\?\(-[0-3][0-9]\)\?,\([0-9][0-9][0-9][0-9]\(-[0-1][0-9]\)\?\(-[0-3][0-9]\)\?\)\?$'
+            echo ${BDC_LIST_RANGE} | grep "${VALID_REGEX}" &> /dev/null || { echo "error: invalid date range \"${BDC_LIST_RANGE}\"" 1>&2; exit 1; }
             ;;
         p)
             BDC_LIST_PATTERN=${OPTARG}
@@ -284,6 +286,8 @@ while getopts "anstr:p:mwuf:ech" FLAG; do
             ;;
         f)
             BDC_LIST_FORMAT=${OPTARG}
+            VALID_REGEX='^\(rel\)$\|^\(abs\)$\|^\(url\)$\|^\(rsync\)$\|^\(xargs-rm\)$\|^\(xargs-curl\)$\|^\(globus=[^ ][^ ]*,[^ ][^ ]*\)'
+            echo ${BDC_LIST_FORMAT} | grep "${VALID_REGEX}" &> /dev/null || { echo "error: invalid format \"${BDC_LIST_FORMAT}\"" 1>&2; exit 1; }
             ;;
         c)
             # hidden option
